#!/bin/bash

# -*- coding: utf-8 -*-
#
# Copyright 2020 - 2022 Vivien Malerba <vmalerba@gmail.com>
#
# This file is part of FAIRSHELL.
#
# FAIRSHELL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FAIRSHELL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FAIRSHELL.  If not, see <http://www.gnu.org/licenses/>.

set +e

# if VM is running, kill it
/usr/share/fairshell/virt-system/vm-tool.py discard-all

# stop service
systemctl stop fairshell-virt-system
systemctl disable fairshell-virt-system

# update security policy
/usr/share/fairshell/virt-system/update-security-policy.py -u

# remove python cache, if any
find /usr/share/fairshell/virt-system -name __pycache__ -type d -exec rm -rf '{}' ';'

# remove Docker images
for tarfile in /usr/share/fairshell/virt-system/docker-images/*.tar
do
    imagename=$(basename "${tarfile%.tar}")
    docker rmi "$imagename"
done

exit 0
